### ISSUE TITLE
I soldered some header pins to the board

### ISSUE THREAD

**Issue by b-morgan** [educ8s/Arduino-Color-E-Paper-Weather-Station#1]
Can you provide a link to the parts you used, please?

**Comment by educ8s** [comment]
You mean the header pins?

**Comment by b-morgan** [comment]
Yes, the header pins. I am a retired software engineer so I often need a little help when it comes to hardware.

**Comment by b-morgan** [comment]
I purchased a sensor with an easyC/Qwiic connector and avoided any soldering at all.
