### ISSUE TITLE
BME280 Sensor

### ISSUE THREAD

**Issue by b-morgan** [educ8s/Arduino-Color-E-Paper-Weather-Station#2]
I didn't have any sensors so I ordered a BME280 sensor. Can you provide some guidance on using this single sensor instead of the two separate, DHT22 and BMP180, sensors?

**Comment by educ8s** [comment]
Sure, you need to connect power, and the other two pins are the SCL and SDA pins. Those pins must be connected to the SDA and SCL pins of the display.

**Comment by b-morgan** [comment]
I was thinking more along the lines of code changes required.
